task:
  name: Build
  persistent_worker: {}
  env:
    USE_CCACHE: 1
    CIRRUS_WORKING_DIR: /tmp/$CIRRUS_REPO_NAME
  clone_script:
    - repo init --depth=1 -u git://github.com/PixelExperience/manifest.git -b twelve || true
  sync_script:
    - rm -rf .repo/local_manifests || true
    - git clone https://github.com/IdkAnythin07/local_manifest.git --depth 1 -b Pixel_exp .repo/local_manifests
    - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
  build_script:
    - source build/envsetup.sh
    - aosp_tissot-userdebug
    - m aex -j$(nproc --all)
  ccache_stats_script:
    - ccache -s
  upload_script: |
    up() {
      curl --upload-file $1 https://transfer.sh/$(basename $1); echo
      # 14 days, 10 GB limit
    }

    up out/target/product/mido/*.zip
